#!/usr/bin/env bash

# Sets up symlinks from this repo into $HOME and hydrates ~/.secrets from macOS Keychain.
# Safe to re-run — existing symlinks are skipped, other files are backed up.

set -euo pipefail

DOTFILES_DIR="$(cd "$(dirname "$0")" && pwd)"

# --- Helpers ---

link_file() {
  local src="$1" dest="$2"
  if [[ -L "$dest" ]]; then
    existing="$(readlink "$dest")"
    if [[ "$existing" == "$src" ]]; then
      echo "  already linked: $dest"
      return
    fi
    echo "  repointing: $dest"
    ln -sfn "$src" "$dest"
  elif [[ -e "$dest" ]]; then
    echo "  backing up: $dest -> $dest.backup"
    mv "$dest" "$dest.backup"
    ln -sfn "$src" "$dest"
  else
    ln -sfn "$src" "$dest"
  fi
  echo "  linked: $dest -> $src"
}

# --- Symlink dotfiles ---

echo "Symlinking dotfiles..."

# Shell
link_file "$DOTFILES_DIR/.zprofile" "$HOME/.zprofile"
link_file "$DOTFILES_DIR/.zshrc" "$HOME/.zshrc"

# Vim and tmux
link_file "$DOTFILES_DIR/.vim" "$HOME/.vim"
link_file "$DOTFILES_DIR/.tmux.conf" "$HOME/.tmux.conf"

# SSH
link_file "$DOTFILES_DIR/.ssh/config" "$HOME/.ssh/config"

# Claude Code
mkdir -p "$HOME/.claude"
link_file "$DOTFILES_DIR/claude/settings.json" "$HOME/.claude/settings.json"
link_file "$DOTFILES_DIR/claude/CLAUDE.md" "$HOME/.claude/CLAUDE.md"

# GitHub Copilot CLI
mkdir -p "$HOME/.copilot"
link_file "$DOTFILES_DIR/copilot/copilot-instructions.md" "$HOME/.copilot/copilot-instructions.md"

# Optional: IntelliJ IdeaVim
# link_file "$HOME/.vim/vimrc" "$HOME/.ideavimrc"

# --- Hydrate ~/.secrets from Keychain ---

secrets_file="$HOME/.secrets"
secrets=(
  FOODIMADE_CF_API_TOKEN
  OPENAI_API_KEY
)

if [[ -n "${CI:-}" ]]; then
  echo "CI detected — skipping secrets hydration."
  exit 0
fi

echo ""
echo "Hydrating ~/.secrets from Keychain..."

{
  echo "# Auto-generated by dotfiles/setup.sh — do not check in"
  for key in "${secrets[@]}"; do
    value="$(security find-generic-password -s "$key" -w 2>/dev/null || true)"
    if [[ -n "$value" ]]; then
      echo "export $key='$value'"
      echo "  found: $key" >&2
    else
      echo "# $key — not found in Keychain"
      echo "  missing: $key (add with: security add-generic-password -s \"$key\" -a \"\$USER\" -w \"<value>\" -U)" >&2
    fi
  done
} > "$secrets_file"
chmod 600 "$secrets_file"

echo "Wrote $secrets_file"
